# Generated by Django 6.0 on 2025-12-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_country_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=10, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(choices=[('general', 'General'), ('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('history', 'History')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
